# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10ac6fed64b283803d17d7d78bbee63c1ade24fd10eb9671e5659ab19576cb3d86610215b3acb00af7678c8361b4327e1e76e4f58630517eb16a36af89b5b520
  app_admin_users: sathibabu.nyros@gmail.com,user2@email.com
  GOOGLE_CLIENT_ID: 197590823023-9t821mcovg3nuh21t10dggubdk3lk21t.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: uCctkEqh1vPbw01Wy_6MdM0x
  
test:
  secret_key_base: 305e397e54e04975b7ddf148d0836e70e0e5f8da8260513ebe80d7f738c70a685e7b838ff24184b5e2ccae3ddb137b8e5befcd69a08c87ef80a8bcf838a9a2b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>




